### ISSUE TITLE
Repeated entries for WildDash

### ISSUE THREAD

**Issue by gyglim** [mseg-dataset/mseg-api#16]
In the WildDash train file list, each entry is repeated 16 times.
Example repetition:
https://github.com/mseg-dataset/mseg-api/blob/master/mseg/dataset_lists/wilddash-19/list/train.txt#L1
https://github.com/mseg-dataset/mseg-api/blob/master/mseg/dataset_lists/wilddash-19/list/train.txt#L71

Is there any particular reason for that or is that an error?

Best,
Michael

**Comment by johnwlambert** [comment]
@gyglim Hi Michael, this is an artifact that can be ignored since we never actual train on WildDash. We had originally duplicated some of the dataloader train lists for small datasets to decrease the overhead between epochs. We measure training time by the number of crops the network sees, as opposed to epochs, so duplication of the length of the train list didn't matter to us.

Before release, we removed that duplication for all the datasets except for WildDash it appears.

**Comment by gyglim** [comment]
Great, thank you for the clarification
